# Generated by Django 4.2.1 on 2023-05-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.CharField(default='https://avatars.mds.yandex.net/i?id=06568aa568af79365d7c1ee286abfcbc805406c7-9180973-images-thumbs&n=13', max_length=2083),
        ),
    ]
